save: "../save/ReacDiff/"
dt_save: 0.01
ini_time: 0.
fin_time: 2.
nx: 1024
xL: 0.
xR: 1.
nu: 5.e-1
rho: 1.e0
CFL: 2.5e-1
if_show: 1
numbers: 2500
if_second_order: 1.
show_steps: 100
init_key: 2022
if_rand_param: False
k_max: 1
N: 2